version: "3.8"

services:
    api_maker:
        image: savainfosystems/api_maker_be_fe:0.0.1-alpha
        container_name: api_maker_be_fe
        ports:
            - '4626:4626'
            - '38246:38246'
            - '38245:38245'
        privileged: true
        platform: linux/amd64
        volumes:
            - ./docker-data/api_maker_config:/root/api_maker_config
        depends_on:
            - am_mongodb
            - am_redis_internal
        network_mode: host
        environment:
            # From this section You can set any environment variable supported by API Maker.
            # https://docs.apimaker.dev/v1/docs/am-resources/api-maker-configurations.html#api-maker-settings
            # - am__cpuCount=1
            - am__serverName=DC_Server_1